name: Test Deno Module

on:
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
      - name: Use Deno Version v1.23.2
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.23.2
      - name: Test Deno Module
        run: deno test tests.ts
